# Generated by Django 4.1.5 on 2023-04-15 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(unique=True, verbose_name='کد')),
                ('publish', models.BooleanField(default=False, verbose_name='انتشار')),
                ('public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
                ('subject', models.CharField(choices=[('sale', 'فروش'), ('mortgage', 'رهن'), ('rent', 'اجاره')], max_length=10, verbose_name='موضوع')),
                ('type', models.CharField(choices=[('land', 'زمین'), ('house', 'خانه'), ('shop', 'مغازه')], max_length=10, verbose_name='نوع')),
                ('land_type', models.CharField(blank=True, choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('res_comm', 'مسکونی - تجاری'), ('garden', 'باغی'), ('rice_field', 'کشاورزی')], max_length=15, null=True, verbose_name='نوع زمین')),
                ('house_type', models.CharField(blank=True, choices=[('villa', 'ویلا'), ('apartment', 'اپارتمان')], max_length=15, null=True, verbose_name='نوع خانه')),
                ('rice_field_type', models.CharField(blank=True, choices=[('mechanized', 'مکانیزه'), ('traditional', 'سنتی')], max_length=15, null=True, verbose_name='نوع زمین کشاورزی')),
                ('address', models.TextField(max_length=250, verbose_name='آدرس')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر/محل')),
                ('area', models.PositiveIntegerField(verbose_name='متراژ')),
                ('all_price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت کل')),
                ('rent', models.BigIntegerField(blank=True, null=True, verbose_name='اجاره ')),
                ('all_rent_price', models.BigIntegerField(blank=True, null=True, verbose_name='ودیعه')),
                ('owner', models.CharField(max_length=30, verbose_name='نام مالک')),
                ('owner_info', models.TextField(max_length=200, verbose_name='مشخصات مالک')),
                ('documents', models.CharField(blank=True, choices=[('deed', 'سند دار'), ('nasaq', 'نسق'), ('arrangement', 'قولنامه ای')], max_length=15, null=True, verbose_name='مدرک')),
                ('exchange', models.BooleanField(default=False, verbose_name='معاوضه')),
                ('inside_plan', models.BooleanField(default=False, verbose_name='داخل طرح')),
                ('points', models.BooleanField(default=False, verbose_name='امتیازات')),
                ('production_license', models.BooleanField(default=False, verbose_name='پروانه ساخت')),
                ('foundation', models.PositiveIntegerField(blank=True, null=True, verbose_name='زیربنا')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طبقه')),
                ('bedroom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('mdf', models.BooleanField(default=False, verbose_name='ام دی اف')),
                ('cooler', models.BooleanField(default=False, verbose_name='کولر')),
                ('water_heater', models.BooleanField(default=False, verbose_name='آبگرمکن')),
                ('elevator', models.BooleanField(default=False, verbose_name='اسانسور')),
                ('video_intercom', models.BooleanField(default=False, verbose_name='آیفون تصویری')),
                ('remote_door', models.BooleanField(default=False, verbose_name='درب ریموت دار')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('warehouse', models.BooleanField(default=False, verbose_name='بهار خواب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(related_name='item_images', to='files.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
